version: "3.9"
services:
  rest-api:
    container_name: rest-api
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: ./
    ports:
      - ${PORT}:${PORT}

  caddy:
    image: caddy/caddy:2.6.4-alpine
    container_name: caddy-service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  volumes:
    caddy_data:
    caddy_config:


