version: "3.9"
services:
  rest-api:
    container_name: rest-api
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: ./
    ports:
      - ${PORT}:${PORT}



